const express = require('express');
const router = express.Router();

const GEMINI_SYSTEM_INSTRUCTION = `
You are KLAPP AI, the official Senior Solutions Architect for KLAPP Developers (founded by Gotti Aashish, 18 years old, 4+ yrs experience).

YOUR PERSONALITY & CONVERSATIONAL STYLE:
- Speak like a friendly, warm, ultra-intelligent human software engineer. Speak in natural English or Telish depending on how the user talks to you.
- Keep answers crisp, structured, engaging, and professional. Use bullet points and clear formatting.
- DO NOT use any Markdown formatting like **bold** or *italics*. Use plain text only.
- MAINTAIN FULL CONVERSATION MEMORY.

COMPANY PORTFOLIO & CASE STUDIES:
- Nandhakam Luxury Stays (Hospitality booking engine with instant WhatsApp alerts)
- Admyra (Fashion e-commerce storefront with Razorpay gateway)
- Chanakya High School (EdTech portal with admissions & parent WhatsApp alerts)
- Balaji Kishore Medical (Pharma inventory & prescription portal)
- Amanvi AI (Autonomous AI customer service platform)
- Seek (Job search & candidate matching portal)

PRICING & PACKAGES:
- Starter Web App: ₹25,000 - ₹35,000
- Custom App & Admin Dashboard: ₹45,000 - ₹75,000
- Enterprise ERP & Meta WhatsApp Bot: ₹50,000 - ₹1,20,000+
`;

/**
 * @route   POST /api/ai/chat
 * @desc    Secure proxy endpoint for Gemini AI Chat
 * @access  Public
 */
router.post('/chat', async (req, res) => {
  try {
    const { message, history } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!message || typeof message !== 'string') {
      return res.status(400).json({ success: false, error: 'Message is required.' });
    }

    if (!apiKey) {
      return res.json({
        success: true,
        reply: "Hello! KLAPP AI backend server is active. To enable live Gemini LLM responses, add your GEMINI_API_KEY to backend/.env!"
      });
    }

    const formattedHistory = Array.isArray(history) ? history.map(m => ({
      role: m.sender === 'user' ? 'user' : 'model',
      parts: [{ text: m.text }]
    })) : [];

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: GEMINI_SYSTEM_INSTRUCTION }] },
        contents: [
          ...formattedHistory,
          { role: 'user', parts: [{ text: message }] }
        ],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 800
        }
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      console.warn('Gemini API Error Response:', errText);
      return res.status(502).json({ success: false, error: 'AI service unavailable.' });
    }

    const data = await response.json();
    if (data.candidates && data.candidates[0] && data.candidates[0].content && data.candidates[0].content.parts[0]) {
      const reply = data.candidates[0].content.parts[0].text.replace(/\*\*/g, '').replace(/\*/g, '');
      return res.json({ success: true, reply });
    }

    return res.status(500).json({ success: false, error: 'No valid output generated by AI model.' });

  } catch (err) {
    console.error('Error in AI Chat proxy:', err);
    return res.status(500).json({ success: false, error: 'Internal Server Error.' });
  }
});

module.exports = router;
